version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:light
    steps:
      - checkout
      - run:
          name: Packer
          command: |
                    packer version
      - run:
          name: Print the Current Time
          command: date